steps:
  - id: "install dependencies"
    name: python:3.9
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
  
  - id: "check formatting"
    name: python:3.9
    entrypoint: black
    args: [".", "--check"]

  - id: "check linting"
    name: python:3.9
    entrypoint: flake8
    args: ["--count", "."]

  - id: "check unused imports"
    name: python:3.9
    entrypoint: python3
    args: ["-m", "autoflake", "-r", "--remove-all-unused-imports", "--check"]

  - id: "check import sorting"
    name: python:3.9
    entrypoint: isort
    args: ["--count", "--profile=black", "."]

  - id: "run unit tests"
    name: python:3.9
    entrypoint: python3
    args: ["td2bq_mapper/tests/test_td2bq.py"]